backend:
  name: git-gateway
  branch: main # ou master

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - file: "content/home.json"
        label: "Página Inicial"
        name: "home"
        fields:
          - { label: "Foto Bloco 1", name: "bloco_img1", widget: "image" }
          - { label: "Foto Bloco 2", name: "bloco_img2", widget: "image" }
